# -*- coding: utf-8 -*-
"""“case—analysis.ipynb”的副本

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cq1OGHJbnOjtVQcoHvj4Oe3o2eXGgx4j
"""

import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

# --- 页面配置 ---
st.set_page_config(page_title="Garment Factory Cost Auditor", layout="wide")

# --- 1. 数据加载与预处理 ---
@st.cache_data
def load_data():
    data = {
        "Metric": ["Labor Cost - Engineer and Management", "Labor Cost - Operator", "Travel", "Company Transportation", "Rent", "Utilities Electricity", "Janitor", "Material Cost", "Machine Maintainance Cost", "Freight", "Insurance", "Depreciation", "Total Sales Qty", "Exchange Rate"],
        "Q1'24": [100, 2000, 20, 200, 40, 2500, 50, 750, 250, 125, 50, 1000, 25000, 4.78],
        "Q2'24": [101, 2230, 30, 203, 41, 2737, 51, 825, 250, 138, 50, 990, 27500, 4.71],
        "Q3'24": [109, 2042, 10, 330, 44, 2588, 55, 701, 250, 117, 50, 980, 23375, 4.37],
        "Q4'24": [107, 2197, 11, 323, 43, 2731, 53, 771, 250, 129, 50, 1000, 25713, 4.47],
        "Q1'25": [115, 2381, 19, 327, 43, 2786, 54, 779, 250, 130, 55, 1200, 25970, 4.42],
        "Q2'25": [120, 2734, 29, 341, 45, 3144, 56, 857, 250, 143, 55, 1400, 28567, 4.23],
        "Q3'25": [120, 2328, 10, 342, 45, 2762, 57, 728, 250, 121, 55, 1400, 24282, 4.22],
        "Q4'25": [122, 2617, 10, 349, 46, 3047, 58, 801, 250, 134, 55, 1500, 26710, 4.13],
        "Q1'26": [132, 3960, 15, 356, 47, 4113, 59, 1122, 250, 187, 55, 1600, 37394, 4.05],
        "Q2'26": [132, 2772, 15, 356, 47, 3056, 59, 785, 250, 131, 55, 1600, 26176, 4.05],
        "Q3'26": [132, 3784, 15, 356, 47, 3179, 59, 825, 250, 137, 55, 1700, 27484, 4.05],
        "Q4'26": [132, 4540, 15, 356, 47, 3697, 59, 989, 250, 165, 55, 1700, 32981, 4.05],
    }
    df = pd.DataFrame(data).set_index("Metric").T

    # 定义分类
    fixed_cols = ["Labor Cost - Engineer and Management", "Rent", "Janitor", "Machine Maintainance Cost", "Insurance", "Depreciation"]
    var_cols = ["Labor Cost - Operator", "Travel", "Company Transportation", "Utilities Electricity", "Material Cost", "Freight"]

    # 核心计算
    df['Total_Fixed'] = df[fixed_cols].sum(axis=1)
    df['Total_Variable'] = df[var_cols].sum(axis=1)
    df['Grand_Total'] = df['Total_Fixed'] + df['Total_Variable']
    df['Cost_Per_Unit'] = df['Grand_Total'] / df['Total Sales Qty']

    # 弹性分析：变动成本增长 vs 产量增长
    df['Qty_Growth'] = df['Total Sales Qty'].pct_change()
    df['Var_Growth'] = df['Total_Variable'].pct_change()
    df['Elasticity'] = df['Var_Growth'] / df['Qty_Growth']

    return df, fixed_cols, var_cols

df, fixed_cols, var_cols = load_data()

# --- 2. 侧边栏与标题 ---
st.title("🏭 Garment Factory Survival Analysis")
st.markdown("---")

# --- Q1: Identify Fixed and Variable Cost ---
st.header("1. Cost Categorization: Fixed vs Variable")
col1, col2 = st.columns([1, 1.5])

with col1:
    latest_q = df.iloc[-1]
    fig_pie = go.Figure(data=[go.Pie(labels=['Fixed Costs', 'Variable Costs'],
                                     values=[latest_q['Total_Fixed'], latest_q['Total_Variable']],
                                     hole=.4, marker_colors=['#2E86C1', '#F39C12'])])
    fig_pie.update_layout(title="Current Cost Structure (Q4'26)")
    st.plotly_chart(fig_pie, use_container_width=True)

with col2:
    st.write("**Cost Behavior Over Time**")
    #
    fig_stack = px.bar(df, y=['Total_Fixed', 'Total_Variable'],
                       title="Cost Mix Trend", barmode='stack',
                       color_discrete_map={'Total_Fixed': '#2E86C1', 'Total_Variable': '#F39C12'})
    st.plotly_chart(fig_stack, use_container_width=True)

# --- Q2: Cost Saving Opportunities ---
st.header("2. Cost Saving Opportunities: Utility & Automation ROI")
col3, col4 = st.columns(2)

with col3:
    st.write("**Efficiency Leak: Utilities vs Production**")
    # 分析电力成本与产量的散点相关性，偏离趋势线的即为浪费
    fig_leak = px.scatter(df, x="Total Sales Qty", y="Utilities Electricity",
                          trendline="ols", size="Cost_Per_Unit",
                          title="Utility Efficiency Audit", color="Cost_Per_Unit")
    st.plotly_chart(fig_leak, use_container_width=True)
    st.caption("Dots above the trendline represent periods of energy inefficiency.")

with col4:
    st.write("**Automation ROI: Depreciation vs Operator CPU**")
    # 如果折旧上升，单位人工成本应该下降
    fig_roi = go.Figure()
    fig_roi.add_trace(go.Scatter(x=df.index, y=df['Depreciation'], name="Depreciation (Investment)", line=dict(width=4)))
    fig_roi.add_trace(go.Scatter(x=df.index, y=df['Labor Cost - Operator']/df['Total Sales Qty']*1000,
                                 name="Operator Cost per 1k Units", yaxis="y2"))
    fig_roi.update_layout(title="Investment vs Labor Efficiency",
                          yaxis=dict(title="Depreciation USD"),
                          yaxis2=dict(title="Labor CPU (Scaled)", overlaying='y', side='right'))
    st.plotly_chart(fig_roi, use_container_width=True)

# --- Q3: Proposal & Challenge ---
st.header("3. Challenges to Cost Owners (Audit Panel)")

# 过滤出弹性系数异常的季度 (> 1.1 说明变动成本增长远超产量增长)
bad_planning = df[df['Elasticity'] > 1.15]

st.warning("🚩 **Management Audit: The following quarters show cost inefficiencies:**")
st.dataframe(bad_planning[['Total Sales Qty', 'Total_Variable', 'Elasticity']].style.background_gradient(cmap='Reds', subset=['Elasticity']))

st.subheader("Actionable Recommendations:")
#
st.info("""
- **Challenge Production Head (Q1'26):** Production volume increased by 40%, but Operator Labor increased by 51%. Why is there a 11% efficiency gap?
- **Utilities Optimization:** Utility CPU peaked in Q2'25 and Q1'26. Audit machine idle time during these periods.
- **FX Hedging:** With exchange rates hitting 4.05, the MYR-denominated margins are under pressure. Recommend renegotiating sales prices if MYR weakens further.
""")

# --- 下一步：导出分析 ---
if st.button("Export Insights to CSV"):
    df.to_csv("factory_audit_report.csv")
    st.success("Report saved successfully!")